version: "3"
   
services:
  ayopop-proxy:
    image: jtl-tkgiharbor.hq.bni.co.id/soadev/ayopop-proxy:0.1
    build: ./source/ayopop-proxy/
    environment:
      HTTPS_PROXY: http://inet.bni.co.id:8080
  graphql:
    image: jtl-tkgiharbor.hq.bni.co.id/soadev/digivouch-graphql:0.1
    build: ./source/graphql/
    ports:
      - 18000:8000
    depends_on:
      - ayopop-proxy
  core-payment:
    image: jtl-tkgiharbor.hq.bni.co.id/soadev/core-payment:0.1
    build: ./source/core-payment/
    environment: 
      CORESERVICE_URL: ${CORESERVICE_URL}    
  ayopop-callback-getter:
    image: jtl-tkgiharbor.hq.bni.co.id/soadev/ayopop-callback-getter:0.1
    build: ./source/ayopop-callback-getter/
    environment: 
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      SQS_URL: ${SQS_URL}
      HTTPS_PROXY: http://inet.bni.co.id:8080
  database-write:
    image: jtl-tkgiharbor.hq.bni.co.id/soadev/database-write:0.1
    build: ./source/database-write/
    environment: 
      DBUSER: ${DBUSER}
      DBPASS: ${DBPASS}
      DBCONN: ${DBCONN}
