version: "3"
   
services:
  ayopop-proxy:
    build: ./source/ayopop-proxy/
    labels:
      - "traefik.http.routers.ayopop-proxy.rule=Host(`ayopop-proxy.docker`)"
  graphql:
    build: ./source/graphql/
    ports:
      - "18000:8000"
    depends_on:
      - ayopop-proxy
    labels:
      - "traefik.http.routers.graphql.rule=PathPrefix(`/graphql`)"
  reverse-proxy:
    image: traefik:v2.4
    command: --api.insecure=true --providers.docker --accesslog=true
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
