version: "3"
   
services:
  ayopop-proxy:
    build: ./source/ayopop-proxy/
    environment:
      HTTPS_PROXY: http://inet.bni.co.id:8080
    labels:
      - "traefik.http.routers.ayopop-proxy.rule=Host(`ayopop-proxy.docker`)"
  graphql:
    build: ./source/graphql/
    ports:
      - 18000:8000
    depends_on:
      - ayopop-proxy
    labels:
      - "traefik.http.routers.graphql.rule=PathPrefix(`/graphql`)"
  database-write:
    build: ./source/database-write/
    environment: 
      DBUSER: ${DBUSER}
      DBPASS: ${DBPASS}
      DBCONN: ${DBCONN}
    labels:
      - "traefik.http.routers.database-write.rule=Host(`database-write.docker`)"
  
